language: cpp
compiler:
  - clang
  - gcc
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle install
script:
  - make dependency
  - make
  - make product
  - bundle exec rake
